#!/bin/ksh

####################################################################
#
#	analog : 24시간의 30분 단위 Log 사용량을 보여주는 Shell입니다
#
#	사용법 : analog (online.log 파일명)
#
####################################################################

echo
echo '0시부터 24시까지 30분 단위로 Log 사용 갯수를 보여드립니다'
echo '미리 online.log 파일을 하루치만 뽑아 두셔야 합니다.'
echo
export TOOL=$HOME/tool
export tty=`tty | nawk -F '/' '{ print $4; }'`

if [ -f $TOOL/tmp/analog${tty}.tmp ]; then rm $TOOL/tmp/analog${tty}.tmp
fi

echo 'export t0000=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0030=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0100=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0130=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0200=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0230=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0300=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0330=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0400=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0430=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0500=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0530=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0600=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0630=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0700=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0730=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0800=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0830=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0900=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t0930=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1000=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1030=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1100=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1130=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1200=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1230=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1300=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1330=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1400=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1430=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1500=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1530=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1600=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1630=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1700=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1730=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1800=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1830=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1900=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t1930=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2000=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2030=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2100=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2130=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2200=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2230=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2300=0' >> $TOOL/tmp/analog${tty}.tmp
echo 'export t2330=0' >> $TOOL/tmp/analog${tty}.tmp

if [ ! "$1" ]
then export filename='online.log'
else export filename=$1
fi

if [ -f $filename ]
then

	for i in `grep 'Complete\.$' $filename | nawk -F ' ' '{ { print $1 } }'`
	do
		export thour=`echo $i | nawk -F ':' '{ { print $1 } }'`
		export tmin=`echo $i | nawk -F ':' '{ { print $2 } }'`
		if [ $tmin -gt 30 ]
		then 
			echo 'export 't$thour`echo 30`'=`expr '\$t$thour`echo 30`' + 1`' >> $TOOL/tmp/analog${tty}.tmp
		else
			echo 'export 't$thour`echo 00`'=`expr '\$t$thour`echo 00`' + 1`' >> $TOOL/tmp/analog${tty}.tmp
		fi
	done

	echo 'echo $t0000' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0030' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0100' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0130' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0200' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0230' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0300' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0330' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0400' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0430' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0500' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0530' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0600' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0630' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0700' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0730' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0800' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0830' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0900' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t0930' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1000' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1030' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1100' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1130' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1200' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1230' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1300' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1330' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1400' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1430' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1500' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1530' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1600' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1630' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1700' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1730' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1800' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1830' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1900' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t1930' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2000' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2030' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2100' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2130' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2200' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2230' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2300' >> $TOOL/tmp/analog${tty}.tmp
	echo 'echo $t2330' >> $TOOL/tmp/analog${tty}.tmp

	chmod 700 $TOOL/tmp/analog${tty}.tmp

	echo 'Out File을 만들까요? \c'
	read yn
	if [ $yn = "y" ]
	then 
		$TOOL/tmp/analog${tty}.tmp > analog.out
	else
		$TOOL/tmp/analog${tty}.tmp
	fi

else

	echo '사용법 : analog (online.log 파일명)'

fi

if [ -f $TOOL/tmp/analog${tty}.tmp ]; then rm $TOOL/tmp/analog${tty}.tmp
fi
