#!/bin/ksh

#########################################################################
#
#   chkcol : Table의 Column과 Data Type을 보여주는 Shell
#                                 표준버전 : v0.2
#
#   사용법 : chkcol table명 [DB명]
#
#########################################################################

# Tool 폴더 설정 ########################################################
if [ ! "$TOOL" ]
then export TOOL=$HOME/tool
fi
#########################################################################


# OS별 awk 설정 #########################################################
if [ `uname` = 'HP-UX' ]
then
   export CAWK=awk
else
   export CAWK=nawk
fi
#########################################################################


# DB명 설정 #############################################################
if [ ! "$2" ]
then
        if [ ! "$DBNAME" ]
        then export dbname="dbname"
        else export dbname=$DBNAME
        fi
else export dbname=$2
fi
#########################################################################

################### Default #############################################

if [ ! "$1" ]
then
	
	echo '사용법 : chkcol table명 [DB명]'
	
else
	
	dbaccess $dbname<<! 1> /dev/null 2> /dev/null
		set isolation to dirty read;
		unload to a.out delimiter ' '
		select c.colname, c.coltype, c.collength, substr(hex(c.collength)::char(10),9,10), t.tabname 
		  from syscolumns c, systables t
		 where t.tabname = "$1"
		   and t.tabid = c.tabid;
!
	cat a.out | nawk -F ' ' '
	{
		printf("%s|", $5);
		
		if ( $2%256 == 0 ) 
			printf("%s|char(%s)", $1, $3);
		else if ( $2%256 == 1 )
			printf("%s|smallint", $1);
		else if ( $2%256 == 2 )
			printf("%s|int", $1);
		else if ( $2%256 == 3 )
			printf("%s|float", $1);
		else if ( $2%256 == 4 )
			printf("%s|smallfloat", $1);
		else if ( $2%256 == 5 )
			if ( $3%256 == 255 )
				printf("%s|decimal(%d)", $1, $3/256);
			else
				printf("%s|decimal(%d,%d)", $1, $3/256, $3%256);
		else if ( $2%256 == 6 )
			printf("%s|serial", $1);
		else if ( $2%256 == 7 )
			printf("%s|date", $1);
		else if ( $2%256 == 8 )
			if ( $3%256 == 255 )
				printf("%s|money(%d)", $1, $3/256);
			else
				printf("%s|money(%d,%d)", $1, $3/256, $3%256);
		else if ( $2%256 == 10 ) 
			printf("%s|datetime %s to %s", $1, idenDT(substr($4,1,1), 1), idenDT(substr($4,2,1), 2));
		else if ( $2%256 == 11 )
			printf("%s|byte", $1);
		else if ( $2%256 == 12 )
			printf("%s|text", $1);
		else if ( $2%256 == 13 )
			if ( int($3/256) == 0 )
				printf("%s|varchar(%d)", $1, $3%256);
			else
				printf("%s|varchar(%d,%d)", $1, $3%256, $3/256);
		else if ( $2%256 == 14 )
			printf("%s|interval %s to %s", $1, idenDT(substr($4,1,1), 1), idenDT(substr($4,2,1), 2));
		else if ( $2%256 == 15 ) 
			printf("%s|nchar(%s)", $1, $3);
		else if ( $2%256 == 16 )
			if ( int($3/256) == 0 )
				printf("%s|nvarchar(%d)", $1, $3%256);
			else
				printf("%s|nvarchar(%d,%d)", $1, $3%256, $3/256);
		else if ( $2%256 == 17 ) 
			printf("%s|int8", $1);
		else if ( $2%256 == 18 ) 
			printf("%s|serial8", $1);
		else if ( $2%256 == 19 ) 
			printf("%s|set", $1);
		else if ( $2%256 == 20 ) 
			printf("%s|multiset", $1);
		else if ( $2%256 == 21 ) 
			printf("%s|list", $1);
		else if ( $2%256 == 40 ) 
			printf("%s|lvarchar(or something like that)", $1);
		else
			printf("%s|unknown", $1);
	
		if ( int($2/256) == 1 )
			printf(" not null\n");
		else
			printf("\n");
	}
	function idenDT (bits, fromto) {
	   if ( bits == "0" )
	      return "year";
		else if ( bits == "2" )
	      return "month";
		else if ( bits == "4" )
	      return "day";
		else if ( bits == "6" )
	      return "hour";
		else if ( bits == "8" )
	      return "minute";
		else if ( bits == "10" )
	      return "second";
		else if ( bits == "11" )
	      return "fraction(1)";
		else if ( bits == "12" )
			if ( fromto == 1 )
	      	return "fraction";
			else
	      	return "fraction(2)";
		else if ( bits == "13" )
	      return "fraction(3)";
		else if ( bits == "14" )
	      return "fraction(4)";
		else if ( bits == "15" )
	      return "fraction(5)";
	   else
	      return "unknown";
	}
	'
	
fi
