#!/bin/ksh

####################################################################         
# 
#   chkcpu : 특정 CPU VP에서 Running 중인 Thread 검사 Shell입니다
#
#   사용법 : chkcpu (CPU VP의 pid) [검사 간격 - 초단위]
#            검사 간격을 입력하지 않을 경우 1초로 한다
#
####################################################################

if [ ! "$1" ]
then
	
	echo
	echo '사용법 : chkcpu (CPU VP의 pid) [검사 간격 - 초단위]'
	
else

	if [ ! "$2" ]
	then export timeslice=1
	else export timeslice=$2
	fi

	while true
	do

		export cnt=0

		echo
		echo '======================================================================'
		date +"%Y년 %m월 %d일  %H시 %M분 %S초"
		echo '----------------------------------------------------------------------'

		export i=`onstat -g glo | nawk -F ' ' '{
					{ if ( $2 == '$1' ) printf("%d%s", $1, $3); }
				 }'`

		for j in `onstat -g ath | grep $i | grep running | nawk -F ' ' '{ {print $3} }'`
		do
			export cnt=`expr $cnt + 1`
			export sid=`onstat -u | grep ^$j | nawk -F ' ' '{ {print $3} }'`
			if [ ! "$sid" ]
			then
				echo 'Check하는 중에 수행이 종료 되었거나, 오류입니다'
			else
				echo 'Session ID : '$sid' ('$i')'
				echo '-------------------------'
				onstat -g ses $sid
				echo '-------------------------'
				export pid=`onstat -g ses | grep ^$sid' ' | nawk -F ' ' '{ {print $4} }'`
				if [ ! "$pid" ]
				then
					echo 'Check하는 중에 수행이 종료 되었거나, 오류입니다'
				else
					echo 'Process ID : '$pid
					echo '-------------------------'
					ps -ef | grep $pid | grep -v 'grep '$pid
				fi
			fi
			echo '----------------------------------------------------------------------'
		done

		echo '해당 Process에 총 '$cnt'개의 Thread가 Running 중입니다'

		sleep $timeslice

	done

fi