#!/bin/ksh

if [ ! "$1" ]
then export sltime=120
else export sltime=$1
fi

echo 
echo '-----------------------------------------------------------'
echo '[5m'$sltime'[0mÃÊ°£ À¯ÁöµÇ´Â Global TransactionÀ» °Ë»öÇÕ´Ï´Ù.'
echo '-----------------------------------------------------------'

export TOOL=$HOME/tool

if [ -f Gxtmp ]; then rm Gxtmp
fi
if [ -f firstGx.tmp ]; then rm firstGx.tmp
fi
if [ -f $TOOL/tmp/secondGx.tmp ]; then rm $TOOL/tmp/secondGx.tmp
fi

onstat -G | grep -v Informix | grep -v active | grep -v Global | grep -v address > firstGx.tmp
/usr/bin/echo '1,$g/^$/d\nw\nq' | ed firstGx.tmp > /dev/null

sleep $sltime

onstat -G | grep -v Informix | grep -v active | grep -v Global | grep -v address > $TOOL/tmp/secondGx.tmp
/usr/bin/echo '1,$g/^$/d\nw\nq' | ed $TOOL/tmp/secondGx.tmp > /dev/null

/usr/bin/echo '1,$s/^/grep "/g\nw\nq' | ed $TOOL/tmp/secondGx.tmp > /dev/null
/usr/bin/echo '1,$s/$/" firstGx.tmp >> Gxtmp/g\nw\nq' | ed $TOOL/tmp/secondGx.tmp > /dev/null


chmod 700 $TOOL/tmp/secondGx.tmp
$TOOL/tmp/secondGx.tmp

if [ -f Gxtmp ]
then
cat Gxtmp
rm Gxtmp
else
echo $sltime'ÃÊ°£ À¯ÁöµÈ Global TransactionÀÌ ¾ø½À´Ï´Ù.'
fi

echo '-----------------------------------------------------------'

if [ -f firstGx.tmp ]; then rm firstGx.tmp
fi
if [ -f $TOOL/tmp/secondGx.tmp ]; then rm $TOOL/tmp/secondGx.tmp
fi
