#!/bin/ksh

####################################################################         
# 
#   droptab : 보관기간이 지난 Table을 Drop하는 Shell입니다
#
#   작성자 : 바니                 작성일자 : 2003년  6월 20일
#                                 최종수정 : 2009년  6월 10일
#
#   사용법 : droptab (현재일자 이전 몇일)
#   요파일 : ds, $TOOL/bin/dbcopy
#
####################################################################

# OS별 awk 설정 #########################################################
if [ `uname` = 'HP-UX' ]
then
   export CAWK=awk
else
   export CAWK=nawk
fi
#########################################################################

export TOOL=$HOME/tool

# G마켓 구분 번호 (반드시 업무계로 배포하여 사용하세요 ☆☆☆☆☆
#export DEVI_NUMB="'DPT0Q00915','DPT0Q00918','DPT0Q00919','DPT0Q00920','DPT0Q00921','DPT0Q01256','DPT0Q01644','DPT0Q01696','DPT0Q01695','DPT0Q01734','DPT0Q02012','DPT0Q02013','DPT0Q02893','DPT0Q02894','DPT0Q02905'"
#export VAN_MEMB_NUMB="'2208183676'"
export TAX_PERS_NUMB="'EBA','GMK','INI','AUC','LGU'"

if [ ! "$1" ]
then export minus=0
else export minus=$1
fi

if [ `env | grep SCHEMADIR | wc -l` -lt 1 ]
then
	export SCHEMADIR=$INFORMIX/SCHEMA
fi 

while true
do ##### Main While Loop

###########################################
#   PB업무계/PB비상승인
###########################################

if [ $INFORMIXSERVER = 'pb01_tcp' ] || [ $INFORMIXSERVER = 'pbsec01_tcp' ]
then 

   echo
   echo '<< PB업무계 >>'
   echo '-------------------------------------------'
   echo '     삭제할 테이블의 유형을 선택하세요'
   echo '-------------------------------------------'
   echo '     1) 일 주기 테이블'
   echo '     2) 월 주기 테이블'
   echo '     0) 빠져 나가기'
   echo '-------------------------------------------'
   echo '     > \c'
   read yn
   echo

   if [ $yn -eq 1 ]; then

      echo
      echo '----------------------------------------'
      echo '   삭제할 테이블 유형을 선택하세요.'
      echo '----------------------------------------'
      echo '   [5m1) 기간만료 1주일 (지연처리 등)[0m'
      echo '   [5m2) 기간만료 한달  (거래내역 등) - 현재없음[0m'
      echo '   3) 백업완료 한달  (직불,구매 등) - 현재없음'
      echo '   4) 백업완료 석달  (포인트 등) - 현재없음'
      echo '   5) 백업완료 12개월 (가맹점 거래고유번호 등) - 현재없음'
      echo '   6) 백업완료 24개월 (승인 등) - 현재없음'
		echo '   7) TLF G마켓 전용으로 전환 3개월 - 현재없음'
      if [ $INFORMIXSERVER = 'pbsec01_tcp' ] || [ $INFORMIXSERVER = 'pbtst01_tcp' ]; then
         echo '   [5m8) 기간만료 1주일 (모니터링 등) - 현재없음[0m'
      fi
      echo '----------------------------------------'
      echo ' >> \c'
      read yn

      if [ $yn = "1" ];   then export period=7 ;  export bu=''
      elif [ $yn = "2" ]; then export period=31;  export bu=''
      elif [ $yn = "3" ]; then export period=31;  export bu='b'
      elif [ $yn = "4" ]; then export period=92;  export bu='b'
      elif [ $yn = "5" ]; then export period=366; export bu='b'
      elif [ $yn = "6" ]; then export period=730; export bu='b'
      elif [ $yn = "7" ]; then export period=92;  export bu='g'
      elif [ $yn = "8" ]; then export period=7;   export bu='m'
      else exit
      fi


      if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
      if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

      dbaccess ksnet<<! 1> /dev/null 2> /dev/null
         set isolation to dirty read;
         unload to $TOOL/tmp/droptab.tmp delimiter ' '
         select first 1 to_char( today - $period - $minus, "%y%m%d" ) tabdate from dual;
!

      export dday=`cat $TOOL/tmp/droptab.tmp`

      if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

      for i in `cat ~informix/SCHEMA/tables_d_$period$bu`
      do
         dbaccess ksnet<<! 1> /dev/null 2> /dev/null
            set isolation to dirty read;
            unload to $TOOL/tmp/droptab.tmp delimiter ' '
            select tabname from systables
             where tabid > 99 and tabtype='T'
               and tabname like '$i%'
               and tabname < '$i$dday'
               and length(tabname) = length('$i$dday')
               and tabname != '${i}yymmdd';
!
         cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
         if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
      done


      #############################
      #   TLF를 G마켓용으로 전환
      #############################
      if [ x$bu = 'xg' ]; then

         echo
         echo '오늘은 '`date +"$ymd"`
         echo '------------------------------'
         echo '[5mG마켓 전용으로 전환할 TLF 테이블들 입니다. (해당 21일분)[0m'
         echo '------------------------------'

         tail -21 $TOOL/tmp/droptab.sql > $TOOL/tmp/droptab.tmp
         mv $TOOL/tmp/droptab.tmp $TOOL/tmp/droptab.sql
         cat $TOOL/tmp/droptab.sql

         echo '------------------------------'
         echo
         echo '전환할까요? \c'
         read yn


         if [ $yn = 'y' ]
         then

            for g in `cat $TOOL/tmp/droptab.sql`
            do
               # G마켓 전용 table을 작업에서 제외 (List 중에서)
               if [ `ds $g | grep data500dbs | wc -l` -gt 0 ]
               then

                  # G마켓 전용 table 생성
                  if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi
                  ds $g | sed -e '/^$/,$d' -e 's/data500dbs  extent size 500000 next size 500000/data10dbs  extent size 10000 next size 10000/g' -e 's/'$g'/new_'$g'/g' > $TOOL/tmp/gmarket.sql
                  dbaccess ksnet $TOOL/tmp/gmarket.sql
                  if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi

                  # G마켓 전용 Table로 G마켓 TLF만 이관
                  $TOOL/bin/dbcopy -f 10000 -l $g.err -h $INFORMIXSERVER -H $INFORMIXSERVER -d ksnet -D ksnet -t $g -T new_$g -s "select * from $g where tax_pers_numb [1,3] in ($TAX_PERS_NUMB)"

                  # G마켓 전용 Table에 Index 생성
                  ds $g | sed -e '1,/revoke/d' -e 's/'$g'/new_'$g'/g' > $TOOL/tmp/gmarket.sql
                  dbaccess ksnet $TOOL/tmp/gmarket.sql
                  if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi

                  # G마켓 전용 Table 통계정보 갱신
                  dbaccess ksnet<<!
                     update statistics high for table new_$g;
!
                  # G마켓 전용 Table을 cctlh로 Rename
                  ds $g | grep "create" | sed -e "s/unique//g" -e "s/\"[A-z]*\".//g" | $CAWK -F ' ' '{ printf("rename %s %s to old_%s;\n", $2, $3, $3); }' > $TOOL/tmp/gmarket.sql
                  ds $g | grep "create" | sed -e "s/unique//g" -e "s/\"[A-z]*\".//g" | $CAWK -F ' ' '{ printf("rename %s new_%s to %s;\n", $2, $3, $3); }' >> $TOOL/tmp/gmarket.sql
                  dbaccess ksnet $TOOL/tmp/gmarket.sql

                  chkext $g
               else
                  echo $g'는 G마켓 전용 Table 입니다.'
               fi
            done

            echo '반드시 old_cctlhyymmdd를 지우세요'
            echo 'n' | tablst2 old_cctlh
            echo

            if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi

         else
            echo '그냥 둡니다'
         fi

      #############################
      #   Table 삭제
      #############################       
      else  
               
         echo  
         echo '오늘은 '`date +"$ymd"`
         echo '------------------------------'
         echo '[5m지우려고 하는 테이블들 입니다.[0m'
         echo '------------------------------'
                  
         cat $TOOL/tmp/droptab.sql
                  
         echo '------------------------------'
         echo
         echo '지울까요? \c'
         read yn  

         if [ $yn = 'y' ]
         then     
                  
            echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
            echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

            dbaccess ksnet $TOOL/tmp/droptab.sql 
                  
         else        
            echo '그냥 둡니다'
         fi
                  
      fi          


   elif [ $yn -eq 2 ]; then 

      echo        
      echo '----------------------------------------'
      echo ' <PB업무계> 삭제할 테이블 유형을 선택하세요.'
      echo '----------------------------------------'
      echo '   [5m1) 기간만료 3달 (단말집계이력)[0m'
      echo '   2) 백업완료 3달 (공인인증MPI)'
      echo '   3) 백업완료 6달 (PG월테이블)'
      echo '   4) 백업완료 1년 (PG현금영수증)'
      if [ $INFORMIXSERVER = 'pbsec01_tcp' ] || [ $INFORMIXSERVER = 'pbtst01_tcp' ]; then
         echo '   [5m5) 기간만료 6달 (모니터링 등)[0m'
      fi    
      echo '----------------------------------------'
      echo ' >> \c'
      read yn

      if [ $yn = "1" ];   then export period=3 ; export bu=''
      elif [ $yn = "2" ]; then export period=3; export bu='b'
      elif [ $yn = "3" ]; then export period=6; export bu='b'
      elif [ $yn = "4" ]; then export period=12; export bu='b'
      elif [ $yn = "5" ]; then export period=6; export bu='m'
      else exit
      fi

      if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
      if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

      dbaccess ksnet<<! 1> /dev/null 2> /dev/null
         set isolation to dirty read;
         unload to $TOOL/tmp/droptab.tmp delimiter ' '
         select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%y%m" ) tabdate from dual;
!

      export themonth=`cat $TOOL/tmp/droptab.tmp`

      if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

      for i in `cat ~informix/SCHEMA/tables_m_$period$bu`
      do
         dbaccess ksnet<<! 1> /dev/null 2> /dev/null
            set isolation to dirty read;
            unload to $TOOL/tmp/droptab.tmp delimiter ' '
            select tabname from systables
             where tabid > 99 and tabtype='T'
               and tabname like '$i%'
               and tabname < '$i$themonth'
               and length(tabname) = length('$i$themonth')
               and tabname != '${i}yymm';
!
         cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
         if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
      done

      echo
      echo '오늘은 '`date +"$ymd"`
      echo '------------------------------'
      echo '[5m지우려고 하는 테이블들 입니다.[0m'
      echo '------------------------------'

      cat $TOOL/tmp/droptab.sql

      echo '------------------------------'
      echo
      echo '지울까요? \c'
      read yn


      if [ $yn = 'y' ]
      then

         echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
         echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

         dbaccess ksnet $TOOL/tmp/droptab.sql

      else
         echo '그냥 둡니다'
      fi

   elif [ $yn -eq 0 ]; then

      echo
      echo '빠이빠이...Goodbye ~~~~ ^oo^'
      exit

   else

      echo
      echo '잘못 입력 하셨습니다.'
      exit

   fi


###########################################
#   정보계
###########################################

elif [ $INFORMIXSERVER = 'mst02_tcp' ] || [ $INFORMIXSERVER = 'tst2_tcp' ]
then 
	
	echo
	echo '<< 정보계 >>'
	echo '-------------------------------------------'
	echo '     삭제할 테이블의 유형을 선택하세요'
	echo '-------------------------------------------'
	echo '     1) 일 주기 테이블'
	echo '     2) 월 주기 테이블'
	echo '     0) 빠져 나가기'
	echo '-------------------------------------------'
	echo '     > \c'
	read yn
	echo

	if [ $yn -eq 1 ]; then

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 1주일  (지연처리 등)[0m'
		echo '   [5m2) 기간만료 한달   (DDC,EDI 등)[0m'
		echo '   3) 백업완료 1주일  (대행승인 등)'
		echo '   4) 백업완료 한달   (PDI 등)'
		echo '   5) 백업완료 두달   (배치승인 등)'
		echo '   6) 백업완료 여섯달 (취소내역 등)'
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ];   then export period=7 ; export bu=''
		elif [ $yn = "2" ]; then export period=31; export bu=''
		elif [ $yn = "3" ]; then export period=7; export bu='b'
		elif [ $yn = "4" ]; then export period=31 ; export bu='b'
		elif [ $yn = "5" ]; then export period=62; export bu='b'
		elif [ $yn = "6" ]; then export period=184; export bu='b'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - $period - $minus, "%Y%m%d" ) tabdate from dual;
!

		export dday=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_d_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$dday'
				   and length(tabname) = length('$i$dday')
				   and tabname != '${i}yyyymmdd';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 2 ]; then 

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 두달   (마이장부 등)[0m'
		echo '   [5m2) 기간만료 두달   (법인카드 등)[0m'
		echo '   [5m3) 기간만료 여섯달 (Okgiro 등)[0m'
		echo '   4) 백업완료 여섯달 (TLF,DDC 등)'
		echo '   5) 백업완료 일년   (salemoney)'
		echo '   6) 백업완료 이년   (강호수 등)'
		echo '   7) 백업완료 삼년   (부가세 등)'
		echo '   8) 백업완료 오년   (전표집계 등)'
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if   [ $yn = "1" ]; then export period=2 ; export bu=''
		elif [ $yn = "2" ]; then export period=5 ; export bu=''
		elif [ $yn = "3" ]; then export period=6 ; export bu=''
		elif [ $yn = "4" ]; then export period=6 ; export bu='b'
		elif [ $yn = "5" ]; then export period=12; export bu='b'
		elif [ $yn = "6" ]; then export period=24; export bu='b'
		elif [ $yn = "7" ]; then export period=36; export bu='b'
		elif [ $yn = "8" ]; then export period=60; export bu='b'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%Y%m" ) tabdate from dual;
!

		export themonth=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_m_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$themonth'
				   and length(tabname) = length('$i$themonth')
				   and tabname != '${i}yyyymm';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 0 ]; then 

		echo
		echo '빠이빠이'
		exit

	else

		echo
		echo '잘못 입력 하셨습니다.'
		exit

	fi
	

###########################################
#   업무계
###########################################

elif [ $INFORMIXSERVER = 'mst01_tcp' ] || [ $INFORMIXSERVER = 'oldsos' ] || [ $INFORMIXSERVER = 'neoecs' ] || [ $INFORMIXSERVER = 'tst_tcp' ]; then

	echo
	echo '<< 업무계 >>'
	echo '-------------------------------------------'
	echo '     삭제할 테이블의 유형을 선택하세요'
	echo '-------------------------------------------'
	echo '     1) 일 주기 테이블'
	echo '     2) 월 주기 테이블'
	echo '     0) 빠져 나가기'
	echo '-------------------------------------------'
	echo '     > \c'
	read yn
	echo

	if [ $yn -eq 1 ]; then

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 1주일 (지연처리 등)[0m'
		echo '   [5m2) 기간만료 한달  (거래내역 등)[0m'
		echo '   3) 백업완료 한달  (직불,구매 등)'
		echo '   4) 백업완료 석달  (포인트 등)'
		echo '   5) 백업완료 12개월 (가맹점 거래고유번호 등)'
		echo '   6) 백업완료 24개월 (승인 등)'
		echo '   7) TLF G마켓 전용으로 전환 3개월'
		if [ $INFORMIXSERVER = 'oldsos' ] || [ $INFORMIXSERVER = 'neoecs' ]; then
			echo '   [5m8) 기간만료 1주일 (모니터링 등)[0m'
		fi
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ];   then export period=7 ;  export bu=''
		elif [ $yn = "2" ]; then export period=31;  export bu=''
		elif [ $yn = "3" ]; then export period=31;  export bu='b'
		elif [ $yn = "4" ]; then export period=92;  export bu='b'
		elif [ $yn = "5" ]; then export period=366; export bu='b'
		elif [ $yn = "6" ]; then export period=730; export bu='b'
		elif [ $yn = "7" ]; then export period=92;  export bu='g'
		elif [ $yn = "8" ]; then export period=7;   export bu='m'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - $period - $minus, "%y%m%d" ) tabdate from dual;
!

		export dday=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_d_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$dday'
				   and length(tabname) = length('$i$dday')
				   and tabname != '${i}yymmdd';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done
		
		#############################
		#   TLF를 G마켓용으로 전환
		#############################
		if [ x$bu = 'xg' ]; then

			echo
			echo '오늘은 '`date +"$ymd"`
			echo '------------------------------'
			echo '[5mG마켓 전용으로 전환할 TLF 테이블들 입니다. (해당 21일분)[0m'
			echo '------------------------------'

			tail -21 $TOOL/tmp/droptab.sql > $TOOL/tmp/droptab.tmp
			mv $TOOL/tmp/droptab.tmp $TOOL/tmp/droptab.sql
			cat $TOOL/tmp/droptab.sql

			echo '------------------------------'
			echo
			echo '전환할까요? \c'
			read yn

			if [ $yn = 'y' ]
			then 

				for g in `cat $TOOL/tmp/droptab.sql`
				do
					# G마켓 전용 table을 작업에서 제외 (List 중에서)
					if [ `ds $g | grep data500dbs | wc -l` -gt 0 ]
					then
					
						# G마켓 전용 table 생성
						if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi
						ds $g | sed -e '/^$/,$d' -e 's/data500dbs  extent size 500000 next size 500000/data10dbs  extent size 10000 next size 10000/g' -e 's/'$g'/new_'$g'/g' > $TOOL/tmp/gmarket.sql
						dbaccess ksnet $TOOL/tmp/gmarket.sql
						if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi
						
						# G마켓 전용 Table로 G마켓 TLF만 이관
						$TOOL/bin/dbcopy -f 10000 -l $g.err -h $INFORMIXSERVER -H $INFORMIXSERVER -d ksnet -D ksnet -t $g -T new_$g -s "select * from $g where tax_pers_numb [1,3] in ($TAX_PERS_NUMB)"
					
						# G마켓 전용 Table에 Index 생성
						ds $g | sed -e '1,/revoke/d' -e 's/'$g'/new_'$g'/g' > $TOOL/tmp/gmarket.sql
						dbaccess ksnet $TOOL/tmp/gmarket.sql
						if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi
							
						# G마켓 전용 Table 통계정보 갱신
						dbaccess ksnet<<!
							update statistics high for table new_$g;
!
					
						# G마켓 전용 Table을 cctlh로 Rename
						ds $g | grep "create" | sed -e "s/unique//g" -e "s/\"[A-z]*\".//g" | $CAWK -F ' ' '{ printf("rename %s %s to old_%s;\n", $2, $3, $3); }' > $TOOL/tmp/gmarket.sql
						ds $g | grep "create" | sed -e "s/unique//g" -e "s/\"[A-z]*\".//g" | $CAWK -F ' ' '{ printf("rename %s new_%s to %s;\n", $2, $3, $3); }' >> $TOOL/tmp/gmarket.sql
						dbaccess ksnet $TOOL/tmp/gmarket.sql
						
						chkext $g
					else
						echo $g'는 G마켓 전용 Table 입니다.'
					fi
				done
				
				echo '반드시 old_cctlhyymmdd를 지우세요'
				echo 'n' | tablst2 old_cctlh
				echo
				
				if [ -f $TOOL/tmp/gmarket.sql ]; then rm $TOOL/tmp/gmarket.sql; fi

			else
				echo '그냥 둡니다'
			fi

		#############################
		#   Table 삭제
		#############################			
		else

			echo
			echo '오늘은 '`date +"$ymd"`
			echo '------------------------------'
			echo '[5m지우려고 하는 테이블들 입니다.[0m'
			echo '------------------------------'

			cat $TOOL/tmp/droptab.sql

			echo '------------------------------'
			echo
			echo '지울까요? \c'
			read yn

			if [ $yn = 'y' ]
			then 

				echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
				echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

				dbaccess ksnet $TOOL/tmp/droptab.sql 

			else
				echo '그냥 둡니다'
			fi
						
		fi

	elif [ $yn -eq 2 ]; then 

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 3달 (단말집계이력)[0m'
		echo '   2) 백업완료 3달 (공인인증MPI)'
		echo '   3) 백업완료 6달 (PG월테이블)'
		echo '   4) 백업완료 1년 (PG현금영수증)'
		if [ $INFORMIXSERVER = 'oldsos' ] || [ $INFORMIXSERVER = 'neoecs' ]; then
			echo '   [5m5) 기간만료 6달 (모니터링 등)[0m'
		fi
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ];   then export period=3 ; export bu=''
		elif [ $yn = "2" ]; then export period=3; export bu='b'
		elif [ $yn = "3" ]; then export period=6; export bu='b'
		elif [ $yn = "4" ]; then export period=12; export bu='b'
		elif [ $yn = "5" ]; then export period=6; export bu='m'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%y%m" ) tabdate from dual;
!

		export themonth=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_m_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$themonth'
				   and length(tabname) = length('$i$themonth')
				   and tabname != '${i}yymm';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 0 ]; then 

		echo
		echo '빠이빠이'
		exit

	else

		echo
		echo '잘못 입력 하셨습니다.'
		exit

	fi



###########################################
#   정보계 제2서버(전자서명 DB)
###########################################

elif [ $INFORMIXSERVER = 'desc01_tcp' ]
then

   echo
   echo '<< 전자서명 DB >>'
   echo '-------------------------------------------'
   echo '     삭제할 테이블의 유형을 선택하세요'
   echo '-------------------------------------------'
   echo '     1) 일 주기 테이블'
   echo '     2) 월 주기 테이블'
   echo '     0) 빠져 나가기'
   echo '-------------------------------------------'
   echo '     > \c'
   read yn
   echo

    if [ $yn -eq 1 ]; then

        echo
        echo '----------------------------------------'
        echo '   삭제할 테이블 유형을 선택하세요.'
        echo '----------------------------------------'
        echo '   4) 백업완료 한달   (signrtlh,desc등)'
        echo '----------------------------------------'
        echo ' >> \c'
        read yn


        if [ $yn = "1" ];   then export period=7 ; export bu=''
        elif [ $yn = "2" ]; then export period=31; export bu=''
        elif [ $yn = "3" ]; then export period=7; export bu='b'
        elif [ $yn = "4" ]; then export period=31 ; export bu='b'
        elif [ $yn = "5" ]; then export period=62; export bu='b'
        elif [ $yn = "6" ]; then export period=184; export bu='b'
        else exit
        fi

        if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
        if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

        dbaccess ksnet<<! 1> /dev/null 2> /dev/null
            set isolation to dirty read;
            unload to $TOOL/tmp/droptab.tmp delimiter ' '
            select first 1 to_char( today - $period - $minus, "%Y%m%d" ) tabdate from dual;
!

        export dday=`cat $TOOL/tmp/droptab.tmp`

        if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

        for i in `cat ~informix/SCHEMA/DESC/tables_d_$period$bu`
        do
            dbaccess ksnet<<! 1> /dev/null 2> /dev/null
                set isolation to dirty read;
                unload to $TOOL/tmp/droptab.tmp delimiter ' '
                select tabname from systables
                 where tabid > 99 and tabtype='T'
                   and tabname like '$i%'
                   and tabname < '$i$dday'
                   and length(tabname) = length('$i$dday')
                   and tabname != '${i}yyyymmdd';
!

            cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
            if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
        done

        echo
        echo '오늘은 '`date +"$ymd"`
        echo '------------------------------'
        echo '[5m지우려고 하는 테이블들 입니다.[0m'
        echo '------------------------------'

        cat $TOOL/tmp/droptab.sql

        echo '------------------------------'
        echo
        echo '지울까요? \c'
        read yn

        if [ $yn = 'y' ]
        then

            echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
            echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

            dbaccess ksnet $TOOL/tmp/droptab.sql

        else
            echo '그냥 둡니다'
        fi


    elif [ $yn -eq 2 ]; then

        echo
        echo '----------------------------------------'
        echo '   삭제할 테이블 유형을 선택하세요.'
        echo '----------------------------------------'
       # echo '   [5m1) 기간만료 두달   (마이장부 등)[0m'
       # echo '   [5m2) 기간만료 두달   (법인카드 등)[0m'
       # echo '   3) 백업완료 여섯달 (TLF,DDC 등)'
       # echo '   4) 백업완료 일년   (salemoney)'
       # echo '   5) 백업완료 이년   (강호수 등)'
       # echo '   6) 백업완료 삼년   (부가세 등)'
       # echo '   7) 백업완료 오년   (전표집계 등)'
        echo '   97) 해당사항 없음. '
        echo '----------------------------------------'
        echo ' >> \c'
        read yn


        if   [ $yn = "1" ]; then export period=2 ; export bu=''
        elif [ $yn = "2" ]; then export period=5 ; export bu=''
        elif [ $yn = "3" ]; then export period=6 ; export bu='b'
        elif [ $yn = "4" ]; then export period=12; export bu='b'
        elif [ $yn = "5" ]; then export period=24; export bu='b'
        elif [ $yn = "6" ]; then export period=36; export bu='b'
        elif [ $yn = "7" ]; then export period=60; export bu='b'
        else exit
        fi

        if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
        if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi


        dbaccess ksnet<<! 1> /dev/null 2> /dev/null
            set isolation to dirty read;
            unload to $TOOL/tmp/droptab.tmp delimiter ' '
            select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%Y%m" ) tabdate from dual;
!

        export themonth=`cat $TOOL/tmp/droptab.tmp`

        if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

        for i in `cat ~informix/SCHEMA/DESC/tables_m_$period$bu`
        do
            dbaccess ksnet<<! 1> /dev/null 2> /dev/null
                set isolation to dirty read;
                unload to $TOOL/tmp/droptab.tmp delimiter ' '
                select tabname from systables
                 where tabid > 99 and tabtype='T'
                   and tabname like '$i%'
                   and tabname < '$i$themonth'
                   and length(tabname) = length('$i$themonth')
                   and tabname != '${i}yyyymm';
!
            cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
            if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
        done

        echo
        echo '오늘은 '`date +"$ymd"`
        echo '------------------------------'
        echo '[5m지우려고 하는 테이블들 입니다.[0m'
        echo '------------------------------'

        cat $TOOL/tmp/droptab.sql

        echo '------------------------------'
        echo
        echo '지울까요? \c'
        read yn

        if [ $yn = 'y' ]
        then
            echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
            echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

            dbaccess ksnet $TOOL/tmp/droptab.sql

        else
            echo '그냥 둡니다'
        fi

    elif [ $yn -eq 0 ]; then

        echo
        echo '빠이빠이'
        exit

    else

        echo
        echo '잘못 입력 하셨습니다.'
        exit

    fi


###########################################
#   정보계 제2서버
###########################################

elif [ $INFORMIXSERVER = 'mst03_tcp' ]
then 
	
	echo
	echo '<< 마이장부 >>'
	echo '-------------------------------------------'
	echo '     삭제할 테이블의 유형을 선택하세요'
	echo '-------------------------------------------'
	echo '     2) 월 주기 테이블'
	echo '     0) 빠져 나가기'
	echo '-------------------------------------------'
	echo '     > \c'
	read yn
	echo

	if [ $yn -eq 2 ]; then 

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   1) 마이장부 2년'
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ];   then export period=24 ; export bu='b'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%Y%m" ) tabdate from dual;
!

		export themonth=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/M03/tables_m_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
 				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$themonth'
				   and length(tabname) = length('$i$themonth')
				   and tabname != '${i}yyyymm';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 0 ]; then 

		echo
		echo '빠이빠이'
		exit

	else

		echo
		echo '잘못 입력 하셨습니다.'
		exit

	fi


###########################################
#   신 마이장부
###########################################

elif [ $INFORMIXSERVER = 'henry_tcp' ]
then 

	# 신 마이장부 이관 중이므로 Block ######
	echo '지우지 마세요'
	exit
	########################################
	
	echo
	echo '<< 신 마이장부 >>'
	echo '-------------------------------------------'
	echo '     삭제할 테이블의 유형을 선택하세요'
	echo '-------------------------------------------'
	echo '     1) 일 주기 테이블'
	echo '     2) 월 주기 테이블'
	echo '     0) 빠져 나가기'
	echo '-------------------------------------------'
	echo '     > \c'
	read yn
	echo

	if [ $yn -eq 1 ]; then

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 1주일  (하모니 등)[0m'
		echo '   [5m2) 기간만료 2주일  (하모니 TLF 후처리 등)[0m'
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ];   then export period=7 ; export bu=''
		elif [ $yn = "2" ];   then export period=14 ; export bu=''
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - $period - $minus, "%y%m%d" ) tabdate from dual;
!

		export dday=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_d_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$dday'
				   and length(tabname) = length('$i$dday')
				   and tabname != '${i}yyyymmdd';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 2 ]; then  

		echo
		echo '----------------------------------------'
		echo '   삭제할 테이블 유형을 선택하세요.'
		echo '----------------------------------------'
		echo '   [5m1) 기간만료 6달 (TLF 등)[0m'
		echo '   2) 백업완료 1년 (신 마이장부)'
		echo '----------------------------------------'
		echo ' >> \c'
		read yn

		if [ $yn = "1" ]; then export period=6 ; export bu=''
		elif [ $yn = "2" ]; then export period=12 ; export bu='b'
		else exit
		fi

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

		dbaccess ksnet<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TOOL/tmp/droptab.tmp delimiter ' '
			select first 1 to_char( today - interval(`expr $period + $minus`) month to month, "%y%m" ) tabdate from dual;
!

		export themonth=`cat $TOOL/tmp/droptab.tmp`

		if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi

		for i in `cat ~informix/SCHEMA/tables_m_$period$bu`
		do
			dbaccess ksnet<<! 1> /dev/null 2> /dev/null
				set isolation to dirty read;
				unload to $TOOL/tmp/droptab.tmp delimiter ' '
				select tabname from systables
 				 where tabid > 99 and tabtype='T'
				   and tabname like '$i%'
				   and tabname < '$i$themonth'
				   and length(tabname) = length('$i$themonth')
				   and tabname != '${i}yyyymm';
!
			cat $TOOL/tmp/droptab.tmp >> $TOOL/tmp/droptab.sql
			if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
		done

		echo
		echo '오늘은 '`date +"$ymd"`
		echo '------------------------------'
		echo '[5m지우려고 하는 테이블들 입니다.[0m'
		echo '------------------------------'

		cat $TOOL/tmp/droptab.sql

		echo '------------------------------'
		echo
		echo '지울까요? \c'
		read yn

		if [ $yn = 'y' ]
		then 

			echo '1,$s/^/drop table /g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null
			echo '1,$s/$/;/g\nw\nq' | ed $TOOL/tmp/droptab.sql > /dev/null

			dbaccess ksnet $TOOL/tmp/droptab.sql 

		else
			echo '그냥 둡니다'
		fi

	elif [ $yn -eq 0 ]; then 

		echo
		echo '빠이빠이'
		exit

	else

		echo
		echo '잘못 입력 하셨습니다.'
		exit

	fi

else

	echo '환경 설정을 다시 확인하세요 ^^'

fi

if [ -f $TOOL/tmp/droptab.tmp ]; then rm $TOOL/tmp/droptab.tmp; fi
if [ -f $TOOL/tmp/droptab.sql ]; then rm $TOOL/tmp/droptab.sql; fi

done ##### Main While Loop
