#!/bin/ksh

#########################################################################
#
#   first1 : 특정 Table의 첫번째 Row를 보여주는 Shell입니다
#
#   사용법 : first1 [Table명] (DB명) (조회할 행 수)
#
#########################################################################

# DB명 설정 #############################################################
if [ ! "$2" ]
then
	if [ ! "$DBNAME" ]
	then export dbname="dbname"
	else export dbname=$DBNAME
	fi
else export dbname=$2
fi
#########################################################################

echo '[0m\c'
################### Default #############################################

if [ ! "$1" ]
then

	echo '사용법 : first1 [Table명] (DB명) (조회할 행 수)'

else

	if [ ! "$3" ]
	then export rows=1
	else export rows=$3
	fi

	dbaccess $dbname<<!
		set isolation to dirty read;
		select first $rows * from $1;
!

fi
