#!/bin/ksh

#########################################################################
#
#   locktable2 : onstat -k의 결과로 Lock 걸린 Object를 보여주는 Shell입니다
#
#   사용법 : locktable2 ( onstat -k의 결과를 저장한 file name )
#   요파일 : onstat -k의 결과를 저장한 file
#
#########################################################################

# Tool 폴더 설정 ########################################################
if [ ! "$TOOL" ]
then export TOOL=$HOME/tool
fi
#########################################################################


# OS별 awk 설정 #########################################################
if [ `uname` = 'HP-UX' ]
then
   export CAWK=awk
else
   export CAWK=nawk
fi
#########################################################################


# 임시파일 초기화 #######################################################
export TempTail=`tty | $CAWK -F/ '{print $4}'`
export TempFile1=$TOOL/tmp/`echo $0 | $CAWK -F '/' '{ print $NF }'`.tmp_${TempTail}
export TempFile2=$TOOL/tmp/`echo $0 | $CAWK -F '/' '{ print $NF }'`.tmp2_${TempTail}

if [ -f $TempFile1 ]; then rm $TempFile1; fi
if [ -f $TempFile2 ]; then rm $TempFile2; fi
#########################################################################


echo '[0m\c'
################### Default #############################################


if [ ! "$1" ]
then

	echo '사용법 : locktable2 ( onstat -k file name )'

else

	for i in `cat $1 | grep -v Informix | grep -v Locks | grep -v active | grep -v address |
					$CAWK -F ' ' '{
										{ print $6; }
					}'`
	do
		export tblsnum="16#"$i
		typeset -i10 tblsnum

		echo 'o\c'
		dbaccess sysmaster<<! 1> /dev/null 2> /dev/null
			set isolation to dirty read;
			unload to $TempFile2 delimiter ' '
			select dbsname, tabname from systabnames
			 where partnum = '$tblsnum';
!
		cat $TempFile2 | $CAWK -F ' ' '{
			{ printf("%-20s %-40s\n", $1, $2);}
		}' >> $TempFile1
	done

	echo "\n--------------------------------------------------------------------"
	echo "[36;43mDatabase Name        Object Name                                    [0m"
	echo "--------------------------------------------------------------------"
	if [ -f $TempFile1 ]
	then
		cat $TempFile1
	else
		echo 'Lock 걸린 Object가 없습니다.'
	fi
	echo "--------------------------------------------------------------------"

	if [ -f $TempFile1 ]; then rm $TempFile1; fi
	if [ -f $TempFile2 ]; then rm $TempFile2; fi

fi
